package io.helstrea.velocity.forwarding;

public enum ForwardingError {
    EMPTY_SECRET,
    SECRET_FILE_MISSING,
    SECRET_FILE_NOT_REGULAR,
    SECRET_FILE_TOO_LARGE,
    SECRET_FILE_INVALID,
    FORWARDING_DISABLED,
    FORWARDING_CLOSED,
    MISSING_RESPONSE,
    TRANSACTION_MISMATCH,
    RESPONSE_ALREADY_CONSUMED,
    RESPONSE_EXPIRED,
    IDENTITY_APPLICATION_FAILED,
    EMPTY_TRUSTED_PROXY_SET,
    INVALID_PROXY_CIDR,
    UNTRUSTED_PROXY,
    PAYLOAD_TOO_SMALL,
    PAYLOAD_TOO_LARGE,
    INVALID_SIGNATURE,
    MALFORMED_PAYLOAD,
    UNSUPPORTED_VERSION,
    INVALID_ADDRESS,
    INVALID_USERNAME,
    TOO_MANY_PROPERTIES,
    TRAILING_DATA
}
