package io.helstrea.velocity.forwarding.paper;

public enum PaperVelocityIssue {
    SERVER_ONLINE_MODE_ENABLED,
    BUNGEECORD_FORWARDING_ENABLED,
    VELOCITY_FORWARDING_DISABLED,
    FORWARDING_SECRET_MISSING,
    FORWARDING_SECRET_MISMATCH,
    PROXY_ONLINE_MODE_MISMATCH
}
